UOS2021/U.O.S-Mobile

app/src/main/res/layout/activity_main.xml
=> Modify main text

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/UofSocket.java
- 소켓 통신을 위한 공용 상수 클래스 내 상수 선언
- 소켓 통신용 클래스(UofSocket) 구현 (소켓 연결 및 데이터 송수신)
=> 안드로이드 소켓 통신 구현

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/MainActivity.java, app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java, app/src/main/java/com/uof/uof_mobile/UofSocket.java, app/src/main/res/layout/activity_sockettest.xml
- 소켓 테스팅용 Activity인 SocketTestActivity 구현
- 소켓 통신시 필요한 권한 추가
- UofSocket 클래스 소켓 null 오류 수정 및 기본 생성자 구현
=> 안드로이드 소켓 테스팅 구현

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/MainActivity.java, app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
- QR 스캔 시 UOF-Mobile 앱 실행
- 스캔된 QR 코드에서 소켓 통신할 서버의 IP 주소와 PORT 번호 추출
- 추출된 IP 및 PORT 번호를 소켓 테스트용 Activity의 변수 및 UI에 등록
=> 안드로이드 QR코드 인식 및 UOF-Mobile 앱 실행

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java, app/src/main/java/com/uof/uof_mobile/UofSocket.java
- 서버 <-> 통신 중 발생한 수신 대기 오류 해결(수신이 2번 이루어지던 부분을 1번으로 수정)
- 수신 데이터 최대 크기 변경 100 -> 1000
- 소켓 연결상태 확인 메소드 반환 값 오류 해결
=> 안드로이드 클라이언트 <-> 서버 소켓 통신 오류 수정

app/src/main/java/com/uof/uof_mobile/SocketTestActivity.java
=> 안드로이드 클라이언트 <-> 서버 소켓 통신 오류 수정 (2)

app/src/main/java/com/uof/uof_mobile/LobbyActivity.java, app/src/main/res/layout/activity_lobby.xml
- UI 버튼 아이디 변경
- LobbyActivity에서 PayActivity, OrderlistActivity, SettingActivity로 화면전환 구현
=> LobbyActivity에서 다른 Activity로 화면 전환 구현

app/src/main/java/com/uof/uof_mobile/LoginActivity.java, app/src/main/res/layout/activity_login.xml
- 회원가입 입력 폼 변수 추가
- 회원가입 입력 정보 확인 메소드 추가
=> U.O.F-Mobile LoginActivity 회원가입 수정

app/src/main/java/com/uof/uof_mobile/LoginActivity.java, app/src/main/res/layout/activity_login.xml
- 회원가입 form 만들었습니다.
- 로그인 페이지에서 밑에 TextView를 클릭 시 회원가입 form 으로 이동하고, 회원가입 form에서 TextView를 터치하면
로그인 form으로 이동하도록 하였습니다.
=> Add function register & Modify LoginActivity design

app/src/main/java/com/uof/uof_mobile/LoginActivity.java, app/src/main/res/layout/activity_login.xml
아이디 필드 선택하면 바로 영어 입력할 수 있도록(나중에 한글입력시 예외처리 해야함)
전화번호 필드 선택시 다이얼만 뜨도록 설정
=> Hotfix Change TextInputLayout inputtype & Java file

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/CardActivity.java, app/src/main/java/com/uof/uof_mobile/HttpManager.java, app/src/main/java/com/uof/uof_mobile/IntroActivity.java, app/src/main/java/com/uof/uof_mobile/LobbyActivity.java, app/src/main/java/com/uof/uof_mobile/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/OrderListActivity.java, app/src/main/java/com/uof/uof_mobile/OrderingActivity.java, app/src/main/java/com/uof/uof_mobile/PayActivity.java, app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/SettingActivity.java, app/src/main/java/com/uof/uof_mobile/UofSocket.java, app/src/main/res/layout/activity_card.xml, app/src/main/res/layout/activity_lobby.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_ordering.xml, app/src/main/res/layout/activity_orderlist.xml, app/src/main/res/layout/activity_qrrecognition.xml, app/src/main/res/layout/activity_setting.xml, app/src/main/res/xml/network_security_config.xml
> 로그인 및 회원가입 시 HttpURLConnection을 사용하여 테스트용 외부서버와 통신
>   
> 통신 설정
>> -  RequestMethod: POST
>> - Content-Type: application/json
>> - Accept: application/json
>> - ConnectTimeout: 2 seconds
>> - ReadTimeout: 2 seconds
> 
> 로그인 및 회원가입은 #16 에 있는 request_code 값을 기준으로 구분되어 처리
=> U.O.F-Mobile <-> 테스트용 외부서버 로그인 및 회원가입 구현

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/UofSocket.java, app/src/main/res/layout/activity_login.xml
> 1) 입력값이 없을 경우 로그인 버튼 비활성화
> 2) 통신 결과값에 따라 ID와 PW 입력칸에 오류 메세지 표시
>
> 오류 메세지(통신)
>> - request_code 0004 => tilLoginId: "아이디가 존재하지 않습니다"
>> - request_code 0005 => tilLoginPw: "비밀번호가 일치하지 않습니다"
>>
>> 위 부분에 대한 토의 필요 #23 
<br>
> 1) 입력값이 없을 경우 회원가입 버튼 비활성화
> 2) 입력값들이 설정한 패턴과 일치하지 않을 경우 오류 메세지 표시
> 3) 통신 결과값에 따라 ID 입력칸에 오류 메세지 표시
>
> 오류 메세지(통신)
>> - request_code 0002 => tilLoginRegisterId: "해당 아이디는 이미 사용중입니다"
>>
> 오류 메세지(패턴)
>> 메소드: checkRegisterId, checkRegisterPw, checkRegisterName, checkRegisterPhoneNumber
>> - 반환값 Constants.Pattern.OK: 설정한 입력값 조건 및 패턴을 만족할 경우
>> - 반환값 Constants.Pattern.LENGTH_SHORT: 설정한 문자열 길이보다 짧을 경우
>> - 반환값 Constants.Pattern.LENGTH_LONG: 설정한 문자열 길이보다 길 경우
>> - 반환값 Constants.Pattern.NOT_ALLOWED_CHARACTER: 입력 허용한 문자 외에 다른 문자가 입력될 경우
=> LoginActivity 내 TextInputLayout 오류 메세지 표시

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/OwnerLobbyActivity.java, app/src/main/java/com/uof/uof_mobile/OwnerQRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/OwnerSettingActivity.java, app/src/main/java/com/uof/uof_mobile/RegisterActivity.java, app/src/main/res/layout/activity_ownerlobby.xml, app/src/main/res/layout/activity_ownerqrrecognition.xml, app/src/main/res/layout/activity_ownersetting.xml, app/src/main/res/layout/activity_register.xml
- 사업자용 Activity: OwnerLobbyActivity, OwnerQRRecognitionActivity, OwnerSettingActivity
=> 사업자용 Activity 및 회원가입 Activity 추가

app/build.gradle, app/src/main/java/com/uof/uof_mobile/LobbyActivity.java, app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java, app/src/main/res/layout/activity_lobby.xml, gradle.properties
- UI 이미지 뷰 ID 변경
- QR 코드 스캐너 구현을 위한 라이브러리 추가 및 QR 코드 스캐너 구현
=> QR 코드 스캐너 구현

app/src/main/AndroidManifest.xml
=> Hotfix Change orientation

app/src/main/java/com/uof/uof_mobile/RegisterActivity.java
=> Hotfix Change JSON Elements

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/QRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/SettingPreferenceFragment.java, app/src/main/res/layout/activity_setting.xml, app/src/main/res/xml/settings_preference.xml
- QR코드 스캔 데이터 중 IP와 Portnumber 값 분리 후 변수에 저장
- SettingActivity 구현
- 진동 설정
- 계정 관리 클릭 이벤트
추후에 계정 관리에서 서버와 연동되는 부분 구현 필요
=> [U.O.F-Mobile] QR코드 스캔 데이터 분리 및 SettingActivity 구현

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java, app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java, app/src/main/res/layout/activity_card.xml, app/src/main/res/values-night/themes.xml
> ### SocketTimeoutException 및 카드제거 클래스(Thread) 추가
> - HttpManager에 SocketTimeoutException 추가 (표시문구: "서버 점검 중입니다")
> - RemoveCard 클래스가 선언만 되어있었음 -> AlertDialog Listener에 실행 코드 추가
> 
<br>
> ### 디자인
>> **1. themes.xml (night)에 있는 카드제거 버튼 스타일명 수정**
>> 
>> **2. 카드 영역 내 "U.O.F" 문구 margin 수정**
> <br>
>
> ### 기능
>> **1. Constants.Network.Response 오류 코드 추가**
>> - code "-1": Unknown error
>> - code "-2": Server is not online
<br>
=> [U.O.F-Mobile] Exception 추가 및 카드제거 오류 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java, app/src/main/java/com/uof/uof_mobile/activity/MovieOrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/PcOrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RestaurantOrderingActivity.java, app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java, app/src/main/res/layout/activity_movieordering.xml, app/src/main/res/layout/activity_ordering.xml, app/src/main/res/layout/activity_pcordering.xml, app/src/main/res/layout/activity_restaurantordering.xml, app/src/main/res/layout/activity_setting.xml, app/src/main/res/layout/dialog_addcard.xml, app/src/main/res/layout/dialog_changephone.xml, app/src/main/res/layout/dialog_changepw.xml, app/src/main/res/layout/dialog_checkpw.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml, app/src/main/res/xml/settings_preference.xml
> ### OrderingActivity 생성
> - 회사 종류(식당, PC방, 영화관)에 따른 주문 Activity 생성
> <br>
>
> **1. RestaurantOrderingActivity, MovieOrderingActivity, PcOrderingActivity 추가**
> 
> **2. U.O.F-Mobile 앱에서 QR이 인식되었을 경우**
> - QRRecognitionActivity에서 정보 수신 후 회사 종류에 따라 각 Activity에 JSONObject를 String으로 전달하도록 구현
> 
> **3. 외부에서 QR이 인식되었을 경우**
> - IntroActivity에서 정보 수신 후 회사 종류에 따라 각 Activity에 JSONObject를 String으로 전달하도록 구현
<br>
> ### 디자인
>> **1. TextInputLayout 테두리 오류 수정**
>> - DialogTheme_FullScreenDialog style을 사용하는 dialog에서 TextInputLayout의 border가 표시되지 않던 오류 수정
>> - background 관련 style 제거
>>
>> **2. TextInputLayout에 입력 형식 적용**
>>
>> **3. PreferenceScreen의 최상단 제목 "설정" 제거 및 커스텀 AppBar 추가**
>>
> <br>
>
> ### 기능
>> **1. Constants.Network 코드 수정**
>> - Request: STORE_PRODUUCT_INFO(0014) 추가
>> - Response: …
=> [U.O.F-Mobile] 회사 종류에 따른 OrderingActivity 생성

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java, app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java, app/src/main/java/com/uof/uof_mobile/manager/SharedPreferenceManager.java, app/src/main/res/xml/network_security_config.xml
> ### 자동로그인 기능
> - 사용자가 수동로그인에 성공할 경우 이후에는 자동로그인
> <br>
>
> **1. SharedPreferenceManager 추가**
> - 자동로그인을 포함한 앱에 관한 여러 정보 저장을 쉽게 저장 및 관리하기 위한 클래스
<br>
> ### 기능
>> **1. SocketManger를 Constants에 선언**
>> - 여러 Activity에서 소켓을 공유해서 사용하기 위함
>> - OrderingActivity부터 PayActivity까지 소켓 통신 유지 시 사용
>>
>> **2. 외부서버 변경에 따른 네트워크 설정 수정**
>> - 변경된 외부서버 도메인 http 허용
<br>
> ### 기능
>> **1. 설정에서 로그아웃 버튼을 눌러 로그아웃 시 자동로그인 해제**
=> [U.O.F-Mobile] 자동로그인 및 네트워크 설정 변경

app/src/main/java/com/uof/uof_mobile/Constants.java, app/src/main/java/com/uof/uof_mobile/Global.java, app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java, app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java, app/src/main/java/com/uof/uof_mobile/activity/SettingActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/CheckPwDialog.java, app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java, app/src/main/java/com/uof/uof_mobile/manager/HttpManager.java, app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java, app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingAdapter.java, app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingProductItem.java, app/src/main/java/com/uof/uof_mobile/recyclerview/OrderingSetItem.java
> **1. Constants 클래스 이름 변경:**
> - Constants -> Global
> <br>
>
> **2. 상위 액티비티 종료 오류 해결**
> - Global.activities에 Activity onCreate() 실행 시 Activity 등록,  onDestroy() 실행 시 Activity 제거
> - SettingPreferenceFragment에서 로그아웃 및 회원 탈퇴 시 상위 액티비티 종료 기능 구현을 위해 사용
=> [U.O.F-Mobile] Hotfix: Constants 클래스명 변경 및 상위 액티비티 종료 오류 해결

app/src/main/java/com/uof/uof_mobile/adapter/BasketAdapter.java
> **1. 장바구니 아이템 삭제 시 발생하는 배열 인덱스 크기 오류 해결**
=> [U.O.F-Mobile] Hotfix: 장바구니 아이템 삭제 오류 해결

app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OrderListActivity.java, app/src/main/java/com/uof/uof_mobile/adapter/OrderListAdapter.java, app/src/main/java/com/uof/uof_mobile/listitem/OrderListItem.java, app/src/main/java/com/uof/uof_mobile/listitem/OrderListProductItem.java, app/src/main/res/layout/activity_orderlist.xml, app/src/main/res/layout/item_orderlist_order.xml
> ### OrderListActivity 구현
> - U.O.F를 통해 주문한 현재까지의 내역을 표시해주는 주문내역 화면 구현
> <br><br>
>
> **1. 주문내역화면에서 보여줄 주문내역 아이템 레이아웃 생성**
> - item_orderlist_order
> <br>
>
> **2. 주문내역  RecyclerView의 데이터를 연결해주는 OrderListAdapter 추가**
<br><br>
> ### 기능
> **1. LobbyActivity에 있는 하단 두 번째 버튼 OrderlistActivity로 변경**
<br><br>
> ### 디자인
> **1. 전반적인 디자인**
> - 폰트 사이즈, 색상 등 구현 필요
> <br><br>
>
> ### 기능
> **1. 외부서버와의 통신을 통한 주문내역 조회**
=> OrderListActivity 구현

app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java, app/src/main/res/layout/activity_ordering.xml, app/src/main/res/layout/dialog_changephone.xml, app/src/main/res/layout/dialog_changepw.xml, app/src/main/res/values/colors.xml
> ### 다이얼로그 디자인 변경
> - 기존 다이얼로그에서 변경사항 적용 시, 버튼을 누르면 적용이 되는 디자인을 오른쪽 위에 Appbar의 변경 TextView를 통해 변경하도록 함.
>
> ### 디자인
> **1. 메뉴 선택하는 OrderingActivity에서 배경을 연한 회색으로 바꾸었습니다. 기존 메뉴의 배경인 흰색이 띄어져 있는 느낌이 들어 변경하였습니다.**
> <br>
> ### 디자인
> **1. 전체적인 Activity Margin 값 조정**
> 
> **2. APP 전체 폰트 변경**
=> [U.O.F Mobile] Change dialog design

app/src/main/java/com/uof/uof_mobile/activity/CardActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/AddCardDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/CardDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePhoneDialog.java, app/src/main/java/com/uof/uof_mobile/dialog/ChangePwDialog.java, app/src/main/java/com/uof/uof_mobile/fragment/SettingPreferenceFragment.java, app/src/main/java/com/uof/uof_mobile/manager/BasketManager.java, app/src/main/java/com/uof/uof_mobile/manager/PatternManager.java, app/src/main/java/com/uof/uof_mobile/other/Card.java, app/src/main/java/com/uof/uof_mobile/other/Global.java, app/src/main/res/drawable/background_button_disabled.xml, app/src/main/res/drawable/background_button_enabled.xml, app/src/main/res/drawable/background_pay_cardenabled.xml, app/src/main/res/layout/activity_card.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_pay.xml, app/src/main/res/layout/activity_register.xml, app/src/main/res/layout/dialog_addcard.xml, app/src/main/res/layout/dialog_card.xml, app/src/main/res/layout/dialog_changephone.xml, app/src/main/res/layout/dialog_changepw.xml, app/src/main/res/layout/dialog_checkpw.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
> ### PayActivity에서 Card 관련 데이터 표시 방식 수정
> <br><br>
>
> **1. 불러온 카드 정보를 저장해두기 위한 Card 클래스 생성**
> - 불필요한 통신을 줄이기 위해 CardDialog 표시 전 불러왔던 카드 데이터를 Card 클래스에 저장
> <br>
>
> **2. PayActivity 내 주문상품 목록 창 크기 변경**
> - 변경 전: wrap_content
> - 변경 후: 352dp (고정: 목록 표시 후 하단에 총 가격이 보이는 크기)
> <br>
>
> **3. 카드 정보가 없을 경우 표시되는 문구 변경**
> - 변경 전: 등록된 카드가 없습니다
> - 변경 후: 터치하여 카드를 등록하세요
> <br>
>
> **4. 불러온 카드 데이터를 card 변수에 저장 시 runOnUiThread 내에서 저장하도록 변경**
> - runOnUiThread에서 card 데이터에 변수 저장 시 runOnUiThread 외부에서 저장할 경우 제대로 표시되지 않는 경우가 있음
> <br>
>
> **5. PayActivity 카드등록 창 표시 방식 변경**
> - 변경 전: CardActivity 호출
> - 변경 후: CardDialog 호출
<br><br>
> ### 디자인
> **1. CardDialog 내 TextInputLayout 변경**
> - inputTupe 및 password toggle icon 표시
> <br>
>
> **2. CardActivity 상단 AppBar UI 디자인 변경**
> <br>
>
> **3. CardDialog 하단에 있던 …
=> [U.O.F-Mobile] PayActivity 구현(카드등록 창) #2

app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/ShowQRDialog.java, app/src/main/res/layout/activity_ownerlobby.xml, app/src/main/res/layout/dialog_showqr.xml
> ### 파트너 로비 페이지 생성
> - 파트너 로비 페이지 생성했습니다
> <br><br>
>
> **1. 이용자가 QR코드를 인식하여 이용할 수 있도록 QR코드 전시하기 버튼을 만들었습니다.**
> 전시하기 버튼을 누르면 ShowQRDialog가 나오며 `ivDlgShowqrQRcode.setImageResource(R.drawable.qrcode);` 에서 Image Resource를 바꿀 수 있습니다.
><br>
> **2. QR코드 불러오기를 통해 포스기에서 해당 업체 앱으로 QR코드를 불러와 저장할 수 있습니다.**
> 포스기와 연동하여 QR코드를 불러올 수 있고 이를 위에 있는 ivDlgShowqrQRcode에 넣어 전시할 수 있습니다. 
또한 포스기와 통신할 때 업체 명을 가져와 `tvOwnerLobbyOwnerName.setText("업체명");` 을 통해 화면에 띄워지는 현재 업체가 어디인지 알 수 있습니다.
> ### 디자인
> **1. U.O.F 로고 제작**
=> [U.O.F Mobile] 파트너 로비 페이지 생성

app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java, app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java, app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java, app/src/main/java/com/uof/uof_mobile/activity/RegisterActivity.java, app/src/main/java/com/uof/uof_mobile/dialog/ShowQRDialog.java, app/src/main/java/com/uof/uof_mobile/other/Global.java, app/src/main/res/layout/activity_ownerlobby.xml, app/src/main/res/layout/activity_register.xml, app/src/main/res/layout/dialog_showqr.xml
> ### U.O.F Partner QR 관리 기능 구현
> <br>
>
> - U.O.F Partner가 QR 인식 시 소켓 통신으로 QR 이미지를 받도록 구현
> <br><br>
>
> **1. QR 인식 시 request_code 0015를 요청**
> <br>
> 
> **2. 전송된 QR코드를 SharedPreferenceManager를 사용하여 스마트폰에 저장**
> <br>
>
> **3. QR 코드 전시하기가 눌릴 경우 기기에 저장된 QR 이미지를 불러와 화면에 표시**
<br><br>
> ### 디자인
> **1. RegisterActivity에서 회사정보 Fab 버튼 클릭 시 숨김**
> <br>
> 
> **2. 회원가입 버튼 디자인을 앱 내 하단 바 디자인과 동일하게 변경**
> <br>
>
> **3. OwnerLobbyActivity, dialog_showqr 내 UI를 AppCompat 형식으로 변경**
> <br><br>
>
> ### 기능
> **1. 결제 버튼 확성화 오류 해결**
> - 비밀번호 입력 및 카드 등록 상태에 따라 결제 버튼 활성화/비활성화
> <br>
> 
> **2.  Global.SharedPreference에 QR 이미지 저장 키 값 추가**
> <br>
>
> **3. QR 코드 불러오기 버튼 리스너 추가**
=> [U.O.F-Mobile] U.O.F Partner QR 관리 기능 구현

app/src/main/java/com/uof/uof_mobile/activity/IntroActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LobbyActivity.java, app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OrderingActivity.java, app/src/main/java/com/uof/uof_mobile/activity/PayActivity.java, app/src/main/java/com/uof/uof_mobile/activity/QRRecognitionActivity.java
> ### 외부 카메라 인식 QR코드 처리
> - IntroActivity -> LoginActivity -> LobbyActivity -> QRRecognitionActivity 순으로 ip와 port 값을 intent로 전달
<br><br>
> ### 기능
> **1. U.O.F 파트너로 QR 인식 시 인식 값이 null인 경우에 대한 예외 처리기능 추가**
=> [U.O.F-Mobile] QR코드를 외부 카메라로 인식 시 처리 기능 구현

app/src/main/res/values/strings.xml
> **1. 어플리케이션 이름 변경: U.O.F-Mobile -> U.O.F**
=> [U.O.F-Mobile] 프로토타입 마무리 #2

app/src/main/java/com/uof/uof_mobile/activity/LoginActivity.java, app/src/main/java/com/uof/uof_mobile/activity/OwnerLobbyActivity.java, app/src/main/java/com/uof/uof_mobile/other/Global.java, app/src/main/res/layout/activity_ownerlobby.xml
> **1. U.O.F 파트너 로그인 시 매장명에 고정된 텍스트가 표시되던 오류 수정**
=> [U.O.F-Mobile] 프로토타입 마무리 #3

app/src/main/java/com/uof/uof_mobile/manager/SocketManager.java, app/src/main/res/layout/activity_ownerlobby.xml
> **1. 관리자 화면 버튼 텍스트 변경 및 margin 변경**
> <br>
>
> **2. 소켓 통신 시 수신 데이터 인코딩 오류로 인한 한글 깨짐 현상 해결**
=> [U.O.F-Mobile] 프로토타입 마무리 #4

app/src/main/java/com/uos/uos_mobile/activity/MovieOrderingActivity.java, app/src/main/java/com/uos/uos_mobile/activity/OrderingActivity.java, app/src/main/java/com/uos/uos_mobile/activity/PayActivity.java, app/src/main/java/com/uos/uos_mobile/adapter/MovieSeatAdapter.java, app/src/main/java/com/uos/uos_mobile/adapter/OrderingAdapter.java, app/src/main/java/com/uos/uos_mobile/dialog/BasketDialog.java, app/src/main/java/com/uos/uos_mobile/dialog/PayResultDialog.java, app/src/main/java/com/uos/uos_mobile/dialog/SelectSeatDialog.java, app/src/main/java/com/uos/uos_mobile/manager/BasketManager.java, app/src/main/java/com/uos/uos_mobile/other/UosFcmService.java, app/src/main/res/drawable/border_seat_reservationavailable.xml, app/src/main/res/drawable/border_seat_selectedseat.xml, app/src/main/res/drawable/border_seat_unreservedseat.xml, build.gradle
> ### 디자인
> **1. 영화좌석 색깔 변경**
> <br><br>
>
> ### 기능
> **1. Gradle 업데이트**
> - 7.0.2 -> 7.0.3
> <br>
>
> **2. OrderingAdapter에서 발생하는 null 오류 해결**
> <br>
>
> **3. MovieOrderingActivity에서 발생하는 ConcurrentModificationException 오류 해결**
> <br>
>
> **4. 사용자가 주문에서 뒤로가기 버튼 누를 시 AlertDialog 표시**
> <br>
>
> **5. Global.Movieseat.None에 대한 else-if 구문 추가**
> <br>
>
> **6. BasketManager 멤버변수 추가**
> - uosPartnerId, companyType, companyName
> <br>
>
> **7. UosFcmService에서 코로나 알림 메세지 변경**
> - 수신된 메세지만 표시하도록 변경
> <br>
>
> **8. 영화관 아이템을 Basket 아이템으로 변환 시 menu에 'N관' 추가**
=> [U.O.S-Mobile] 오류 수정 및 gradle 업데이트
